### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dcconner** [KavenYau/ros2_astra_camera#1]
trying to build under Ubuntu 20.04 with ROS 2 Foxy 

`In file included from ros2_foxy/src/ros2_astra_camera/ros2_astra_camera/src/astra_wrapper/astra_device.cpp:33:
ros2_foxy/src/ros2_astra_camera/ros2_astra_camera/include/ros2_astra_camera/astra_wrapper/astra_device.h:65:14: error: ‘function’ in namespace ‘std’ does not name a template type
   65 | typedef std::function<void(sensor_msgs::msg::Image::SharedPtr image)>
      |              ^~~~~~~~
ros2_foxy/src/ros2_astra_camera/ros2_astra_camera/include/ros2_astra_camera/astra_wrapper/astra_device.h:53:1: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
   52 | #include <sensor_msgs/msg/image.hpp>
  +++ |+#include <functional>
   53 | #include <string>
ros2_foxy/src/ros2_astra_camera/ros2_astra_camera/include/ros2_astra_camera/astra_wrapper/astra_device.h:123:27: error: ‘FrameCallbackFunction’ has not been declared
  123 |   void setIRFrameCallback(FrameCallbackFunction callback);
      |                           ^~~~~~~~~~~~~~~~~~~~~
ros2_foxy/src/ros2_astra_camera/ros2_astra_camera/include/ros2_astra_camera/astra_wrapper/astra_device.h:124:30: error: ‘FrameCallbackFunction’ has not been declared
  124 |   void setColorFrameCallback(FrameCallbackFunction callback);
      |                              ^~~~~~~~~~~~~~~~~~~~~
`

What is the status of this code?  Looks like you have just started development. Is it working for you?

**Comment by KavenYau** [comment]
Thanks for opening issue. 

I make this package due to I can't find an available official one. So far it can meet my need, But if not in future, it will continue to be updated.

**Comment by KavenYau** [comment]
With applying this patch(f230765cd1efbc0d4408b4978483cd1c76892ff3), it could be build on foxy.
