### ISSUE TITLE
DeviceOpen using default: no devices found

### ISSUE THREAD

**Issue by miku54** [KavenYau/ros2_astra_camera#3]
Hi, I use the astra pro camera in the foxy system. After I cloned this repository, I compiled it successfully. After copying the rules file (56-orbbec-usb.rules) to /etc/udev/rules.d/, I start the camera:
When ros2 launch ros2_astra_camera astra_pro_launch.py, the terminal prints an error: "DeviceOpen using default: no devices found"
I can see from v4tl that the system has recognized the astra pro camera, use lsusb | grep 2bc5 to check the camera's VID:PID string is 2bc5:0502
sudo service udev reload && sudo service udev restart
This command didn't solve my problem. Is there any good solution please?
![lQLPDhtl-eXebI3NAoHNBC2wbqOBG-5SKVcCd8A9dICfAA_1069_641](https://user-images.githubusercontent.com/81612531/167100264-3b987153-49b7-4884-b24f-827c046db66d.png)
![7E556304-5A04-42c8-98A7-F4F8C64ACC59](https://user-images.githubusercontent.com/81612531/167100279-4ba71db4-4165-4a47-a190-3e72f5ff25c7.png)

![5B40B438-157B-4971-8C5E-BB79D3B75796](https://user-images.githubusercontent.com/81612531/167100298-739adbb9-481f-41d0-ae16-dc1ce7f21622.png)

**Comment by KavenYau** [comment]
Hi, it seems that your astra pro is the same as mine. Is there any device under `/dev` directory? you can check with this command. Repluging the device may help too.
```sh
ls -al /dev/astra*
```

**Comment by miku54** [comment]
Hi, thanks for your reply!
There are devices in the /dev directory, the device number is video0
After replugging the device and starting the camera, it still doesn't solve the problem.![image](https://user-images.githubusercontent.com/81612531/167108037-5e4afa94-c419-4936-a2aa-8ebdbb24e4d6.png)

**Comment by KavenYau** [comment]
Too odd! Everything looks normal. What platform are you using? Did you test on PC？

**Comment by miku54** [comment]
I am using a Jetson nano board, armv8 architecture, and everything works fine in a PC (windows10) .                                                     T^T

**Comment by KavenYau** [comment]
😅 , I only have Jetson Xavier NX, but currently I don't have time to test.

**Comment by miku54** [comment]
If it's convenient, can you send me a picture of your camera?

**Comment by KavenYau** [comment]
The main reason is astra_camera_node wrongly links to libOpenNI2.so which installed in system. A temporary solution is setting LD_LIBRARY_PATH environment to the right path of libOpenNI2.so. 
e.g. `export LD_LIBRARY_PATH=~/ros2_ws/src/ros2_astra_camera/ros2_astra_camera/lib/openni2_redist/arm64`

**Comment by miku54** [comment]
If it's convenient, can you send me a picture of your camera?
「Kaven Yau ***@***.***>」在 2022年5月7日 週六，08:20 寫道：
