### ISSUE TITLE
运行有问题

### ISSUE THREAD

**Issue by qian-mo** [KavenYau/ros2_astra_camera#4]
老哥，我用的Ubuntu server 20和foxy，用的一块arm的板子，编译没问题，启动的时候有这样的报错，麻烦看一下

`sunrise@ubuntu:~$ ros2 launch ros2_astra_camera astra_pro_launch.py
[INFO] [launch]: All log files can be found below /home/sunrise/.ros/log/2022-05-26-04-25-36-283978-ubuntu-3964
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [3977]
[INFO] [astra_camera_node-2]: process started with pid [3979]
[INFO] [uvc_camera_node-3]: process started with pid [3981]
[INFO] [robot_state_publisher-4]: process started with pid [3983]
[robot_state_publisher-4] [WARN] [1653539137.403839068] [robot_state_publisher]: No robot_description parameter, but command-line argument available.  Assuming argument is name of URDF file.  This backwards compatibility fallback will be removed in the future.
[robot_state_publisher-4] Parsing robot urdf xml string.
[robot_state_publisher-4] Link camera_depth_frame had 1 children
[robot_state_publisher-4] Link camera_depth_optical_frame had 0 children
[robot_state_publisher-4] Link camera_rgb_frame had 1 children
[robot_state_publisher-4] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-4] [INFO] [1653539137.438921342] [robot_state_publisher]: got segment camera_depth_frame
[robot_state_publisher-4] [INFO] [1653539137.439123972] [robot_state_publisher]: got segment camera_depth_optical_frame
[robot_state_publisher-4] [INFO] [1653539137.441381730] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-4] [INFO] [1653539137.441516900] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-4] [INFO] [1653539137.441604277] [robot_state_publisher]: got segment camera_rgb_optical_frame
[component_container-1] [INFO] [1653539137.459654758] [depth_image_proc_container]: Load Library: /opt/tros/lib/libdepth_image_proc.so
[astra_camera_node-2] [INFO] [1653539137.486728564] [astra_wrapper]: Device "2bc5/060e@1/9" found.
[astra_camera_node-2] [INFO] [1653539137.521896632] [astra_camera_node]: ir_frame_id = 'camera_ir_optical_frame'
[astra_camera_node-2] [INFO] [1653539137.522587564] [astra_camera_node]: rgb_frame_id = 'camera_rgb_optical_frame'
[astra_camera_node-2] [INFO] [1653539137.522764901] [astra_camera_node]: depth_frame_id = 'camera_depth_optical_frame'
[astra_camera_node-2] [INFO] [1653539137.528327524] [astra_camera_node]: initDevice
[astra_camera_node-2] Warning: USB events thread - failed to set priority. This might cause loss of data...
[astra_camera_node-2] Warning: USB events thread - failed to set priority. This might cause loss of data...
[astra_camera_node-2] [INFO] [1653539137.718840395] [astra_wrapper]: device name: Orbbec Dabai
[astra_camera_node-2] [INFO] [1653539137.719998837] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539137.720266468] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539137.720473431] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [WARN] [1653539137.948407128] [astra_camera_node]: has IR sensor is 1
[component_container-1] [INFO] [1653539138.034633619] [depth_image_proc_container]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::ConvertMetricNode>
[component_container-1] [INFO] [1653539138.034889375] [depth_image_proc_container]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::CropForemostNode>
[component_container-1] [INFO] [1653539138.034987836] [depth_image_proc_container]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::DisparityNode>
[component_container-1] [INFO] [1653539138.035063212] [depth_image_proc_container]: Found class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyzNode>
[component_container-1] [INFO] [1653539138.035132422] [depth_image_proc_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depth_image_proc::PointCloudXyzNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/point_cloud_xyz_node' in container '/depth_image_proc_container'
[uvc_camera_node-3] [WARN] [1653539138.131601066] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[uvc_camera_node-3] [INFO] [1653539138.195969329] [uvc_camera_node]: Opening camera with vendor=0x2bc5, product=0x50e, serial="", index=0
[uvc_camera_node-3] unsupported descriptor subtype VS_COLORFORMAT
[uvc_camera_node-3] [INFO] [1653539138.316305128] [uvc_camera_node]: uvc mode: 640x480@30.000000 uncompressed
[uvc_camera_node-3] attempt to claim already-claimed interface 1
[astra_camera_node-2] [INFO] [1653539138.420367065] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.420580445] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.420672197] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.421683928] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.421937350] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.422366193] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.423695389] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.423950020] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.424135732] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.462057325] [astra_camera_node]: Starting IR stream.
[astra_camera_node-2] [WARN] [1653539138.503268949] [astra_camera_node]: has depth sensor is 1
[astra_camera_node-2] [INFO] [1653539138.513408924] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.513696805] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.513874434] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.515016210] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.516655788] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.516868417] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.517988484] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.518278574] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.518652165] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.533578164] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.533915880] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.534089050] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.535064363] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.535343245] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.536203889] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[astra_camera_node-2] [INFO] [1653539138.537364414] [astra_camera_node]: depth_mode is Resolution: 640x480@30Hz Format: Depth 1mm
[astra_camera_node-2] [INFO] [1653539138.537615795] [astra_camera_node]: color mode is Resolution: 640x480@30Hz Format: RGB888
[astra_camera_node-2] [INFO] [1653539138.538597442] [astra_camera_node]: IR mode is Resolution: 640x480@30Hz Format: Gray16
[ERROR] [astra_camera_node-2]: process has died [pid 3979, exit code -11, cmd '/home/sunrise/limo_ros2/install/ros2_astra_camera/lib/ros2_astra_camera/astra_camera_node --ros-args -r __node:=astra_camera_node --params-file /home/sunrise/limo_ros2/install/ros2_astra_camera/share/ros2_astra_camera/launch/params/astra_pro.yaml'].`

**Comment by KavenYau** [comment]
```log
[uvc_camera_node]: Opening camera with vendor=0x2bc5, product=0x50e, serial="", index=0 
[uvc_camera_node-3] unsupported descriptor subtype VS_COLORFORMAT 
[uvc_camera_node-3] [INFO] [1653539138.316305128] 
[uvc_camera_node]: uvc mode: 640x480@30.000000 uncompressed 
[uvc_camera_node-3] attempt to claim already-claimed interface 1 
```

I found some errors in your logs,  you could run the `v4l2-ctl --list-formats-ext` command to determine the acceptable values for your camera, then try to set another uvc mode and launch again.
