### ISSUE TITLE
can not find device

### ISSUE THREAD

**Issue by heacens** [KavenYau/ros2_astra_camera#5]
I used this package and set the ruled file，" ls  /dev " find astra device is ok，when run the launch py，error with “No matching device found.... waiting for devices. Reason: astra_camera::AstraDevice::AstraDevice(const string&) ”，I debuged find "oniGetDeviceList(&m_pDeviceInfos, &m_deviceInfoCount);" did not get device, did you meet this problem?

**Comment by KavenYau** [comment]
I think it's a similar case like https://github.com/KavenYau/ros2_astra_camera/issues/3#issuecomment-1140633159.
Could you set LD_LIBRARY_PATH environment variable and try again?

**Comment by heacens** [comment]
> I think it's a similar case like [#3 (comment)](https://github.com/KavenYau/ros2_astra_camera/issues/3#issuecomment-1140633159). Could you set LD_LIBRARY_PATH environment variable and try again?

Thank you very much, the problem is solved and device find.
